# Generated by Django 5.1.3 on 2024-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='blogs/blog.jpg', upload_to='blogs/'),
        ),
    ]
